
version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: rag_backend
    ports:
      - "8000:8000"  # Map FastAPI's port
    volumes:
      - ./backend:/app  # Optional, for local dev
    env_file:
      - .env


  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: rag_frontend
    ports:
      - "8501:8501"  # Map Streamlit's port
    depends_on:
      - backend
    env_file:
      - .env

